# Generated by Django 4.2.1 on 2024-04-30 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pollution'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pollution',
            options={'ordering': ('date',)},
        ),
    ]
